// TRY - CATCH

    const numero1 = 100
    const numero2 = 300
    try {
        console.log(numero1)
            console.log(numero2)
            console.log(numero3)
    } catch (error) {
        console.log(error);
    }